name: toolchain-build
description: 'Builds the selected toolchain'

inputs:
  tools-version:
    description: Which toolchain to build
    required: false
    default: 'riscv-tools'
  cache-key:
    description: Use this for caching
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      id: toolchain-build-id
      with:
        path: ${{ inputs.tools-version }}-install
        key: ${{ inputs.cache-key }}
    - name: run build toolchain if not cached
      run: |
        if [[ "${{ steps.toolchain-build-id.outputs.cache-hit }}" != 'true' ]]; then
          echo "Cache miss on ${{ inputs.tools-version }}-install"
          ./.github/scripts/build-toolchains.sh ${{ inputs.tools-version }}
        else
          echo "cache hit do not generate build ${{ inputs.tools-version }}"
        fi
      shell: bash

