name: toolchain-build
description: 'Build/cache both toolchains'

runs:
  using: "composite"
  steps:
    - name: Generate hashes
      run: .github/scripts/create-hash.sh
      shell: bash

    - name: Cache riscv-tools
      uses: actions/cache@v2
      with:
        path: riscv-tools-install
        key: riscv-tools-installed-${{ env.tools-cache-version }}-${{ hashFiles('**/riscv-tools.hash') }}

    - name: Build RISC-V toolchain if not cached
      run: ./.github/scripts/build-toolchains.sh riscv-tools
      shell: bash

    - name: Cache esp-tools
      uses: actions/cache@v2
      with:
        path: esp-tools-install
        key: esp-tools-installed-${{ env.tools-cache-version }}-${{ hashFiles('**/esp-tools.hash') }}

    - name: Build ESP RISC-V toolchain if not cached
      run: ./.github/scripts/build-toolchains.sh esp-tools
      shell: bash
