name: run-tests
description: 'Runs tests according to input parameters'

inputs:
<<<<<<< HEAD
=======
  tools-version:
    description: Which toolchain to build
    required: false
    default: 'riscv-tools'
>>>>>>> 52c752ba... Move Chipyard CI to Github Actions
  group-key:
    description: group key
    required: true
  project-key:
    description: project key
    required: true
  run-script:
    description: rtl build script to use
    required: false
    default: "run-tests.sh"

runs:
  using: "composite"
  steps:
<<<<<<< HEAD
    - name: Init submodules (since only the RTL is cached)
      run: ./scripts/init-submodules-no-riscv-tools.sh
      shell: bash

    # Note: You shouldn't need the other inputs since it shouldn't build RTL from scratch
    - name: Build RTL
      uses: ./.github/actions/prepare-rtl
      with:
        group-key: ${{ inputs.group-key }}

    - name: Run RTL tests
      run: ./.github/scripts/${{ inputs.run-script }} ${{ inputs.project-key }}
      shell: bash
=======
    - name: run rtl build script cache of chipyard root should have been loaded by prepare-rtl
      run: |
        export RISCV="/__w/chipyard/chipyard/riscv-tools-install"
        export LD_LIBRARY_PATH="$RISCV/lib"
        export PATH="$RISCV/bin:$PATH"
        ./.github/scripts/${{ inputs.run-script }} ${{ inputs.project-key }}
      shell: bash

>>>>>>> 52c752ba... Move Chipyard CI to Github Actions
