name: chipyard-ci-full-flow

on:
  # run ci on pull requests targeting following branches (runs on the merge commit)
  pull_request:
    branches:
      - main
      - '1.[0-9]*.x'

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  REMOTE_WORK_DIR: ${{ secrets.BUILDDIR }}/cy-ci-shared/cy-${{ github.sha }}
  JAVA_TMP_DIR: /tmp/cy-${{ github.sha }}-full

jobs:
  cancel-prior-workflows:
    name: cancel-prior-workflows
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  # Set up a set of boolean conditions to control which branches of the CI
  # workflow will execute This is based off the conditional job execution
  # example here: https://github.com/dorny/paths-filter#examples
  change-filters:
    name: filter-jobs-on-changes
    runs-on: ubuntu-latest
    # Queried by downstream jobs to determine if they should run.
    outputs:
      needs-rtl: ${{ steps.filter.outputs.all_count != steps.filter.outputs.skip-rtl_count }}

    steps:
      - uses: actions/checkout@v3
      - name: Git workaround
        uses: ./.github/actions/git-workaround
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            all:
              - '**'

            # If any of the files changed match, do a doc build
            docs: &docs-filter
              - 'docs/**'
              - '.readthedocs.yml'

            # If all files match to this filter, skip the main ci pipeline
            skip-rtl:
              - *docs-filter
              - '**/*.md'
              - '**/.gitignore'
              - '.github/ISSUE_TEMPLATE/**'

  setup-repo:
    name: setup-repo
    needs: [change-filters, cancel-prior-workflows]
    if: needs.change-filters.outputs.needs-rtl == 'true'
    runs-on: ferry
    steps:
      - name: Delete old checkout
        run: |
            ls -alh .
            rm -rf ${{ github.workspace }}/* || true
            rm -rf ${{ github.workspace }}/.* || true
            ls -alh .
      - uses: actions/checkout@v3
      - name: Setup repo copy
        run: |
          git clone $GITHUB_WORKSPACE ${{ env.REMOTE_WORK_DIR }}
      - name: Setup repo
        run: |
          cd ${{ env.REMOTE_WORK_DIR }}
          eval "$(conda shell.bash hook)"
          mkdir ${{ env.JAVA_TMP_DIR }}
          export MAKEFLAGS="-j32"
          ./build-setup.sh -f

  run-cfg-finder:
    name: run-cfg-finder
    needs: [setup-repo]
    runs-on: ferry
    steps:
      - name: Run config finder
        run: |
          cd ${{ env.REMOTE_WORK_DIR }}
          eval "$(conda shell.bash hook)"
          source env.sh
          cd sims/verilator
          make find-config-fragments

  run-tutorial:
    name: run-tutorial
    needs: [setup-repo]
    runs-on: ferry
    steps:
      - name: Run smoke test
        run: |
          cd ${{ env.REMOTE_WORK_DIR }}
          eval "$(conda shell.bash hook)"
          source env.sh
          cd sims/verilator
          make verilog
      - name: VLSI test
        run: |
          cd ${{ env.REMOTE_WORK_DIR }}
          eval "$(conda shell.bash hook)"
          source env.sh

          cd vlsi
          export tutorial=sky130-openroad

          # NOTE: most conda installs are in separate conda envs because they mess up each other's versions (for no apparent reason)

          # installs for example-sky130.yml
          conda create -y --prefix ./.conda_sky130 open_pdks.sky130a=1.0.399_0_g63dbde9
          git clone https://github.com/rahulk29/sram22_sky130_macros.git
          echo "" >> example-sky130.yml
          echo "# tutorial configs" >> example-sky130.yml
          echo "technology.sky130.sky130A: $PWD/sky130/share/pdk/sky130A" >> example-sky130.yml
          echo "technology.sky130.sram22_sky130_macros: $PWD/sram22_sky130_macros" >> example-sky130.yml
          make buildfile

          # installs for example-openroad.yml
          # yosys
          conda create -y --prefix ./.conda_yosys yosys=0.27_4_gb58664d44
          echo "" >> example-openroad.yml
          echo "# tutorial configs" >> example-openroad.yml
          echo "synthesis.yosys.yosys_bin: $PWD/.conda_yosys/bin/yosys" >> example-openroad.yml
          make syn
          
          # remaining tools
          # conda create -y --prefix ./.conda_openroad openroad=2.0_7070_g0264023b6
          # conda create -y --prefix ./.conda_openroad
          # conda activate ./.conda_openroad
          # conda install -y -c litex-hub openroad=2.0_7070_g0264023b6
          # conda create -y --prefix ./.conda_klayout klayout=0.28.5_98_g87e2def28
          # echo "par.openroad.openroad_bin: $PWD/.conda_openroad/bin/openroad" >> example-openroad.yml
          # echo "par.openroad.klayout_bin: $PWD/.conda_klayout/bin/klayout" >> example-openroad.yml
          
          conda create -y --prefix ./.conda_signoff magic netgen
          echo "drc.magic.magic_bin: $PWD/.conda_signoff/bin/magic" >> example-openroad.yml
          echo "lvs.netgen.netgen_bin: $PWD/.conda_signoff/bin/netgen" >> example-openroad.yml
          conda deactivate
          
          # # normal chipyard setup
          # cd ${{ env.REMOTE_WORK_DIR }}
          # source env.sh
          
          # vlsi flow
          # cd vlsi
          
          # TODO: consider setting VLSI_TOP=RocketTile
          # make buildfile
          # make syn
          # make par

  cleanup:
    name: cleanup
    needs: [run-tutorial]
    runs-on: ferry
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    steps:
      - name: Delete repo copy and conda env
        run: |
           rm -rf ${{ env.REMOTE_WORK_DIR }}
