name: weekly-tag

on: workflow_dispatch

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest semver tag, add +1 to minor version (drop patch), generate tag for it
        run: |
          NEWSEMVER=$(echo $(git describe --abbrev=0 --tags) | awk -F'[.]'  '{
          major=$1;
          minor=$2;
          minor += 1;
          printf( "%d.%d.0\n", major, minor );
          }')
          echo "Tagging with $NEWSEMVER"
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/git/refs \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --data @- << EOF
          {
            "ref": "refs/tags/$NEWSEMVER",
            "sha": "${{ github.sha }}"
          }
          EOF
